// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiFKRecExample.Models;

namespace MultiFKRecExample.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201226222449_ImmunizationDesc")]
    partial class ImmunizationDesc
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("MultiFKRecExample.Models.Immunization", b =>
                {
                    b.Property<int>("ImmunizationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ImmunizationID")
                        .UseIdentityColumn();

                    b.Property<string>("ImmunizationDesc")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("ImmunizationDesc");

                    b.HasKey("ImmunizationID");

                    b.ToTable("Immunizations");
                });

            modelBuilder.Entity("MultiFKRecExample.Models.ImmunizationRecord", b =>
                {
                    b.Property<int>("PatientImmunizationRecordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RecordID")
                        .UseIdentityColumn();

                    b.Property<string>("ImmunizationDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ImmunizationID")
                        .HasColumnType("int")
                        .HasColumnName("ImmunizationID");

                    b.Property<int>("PatientID")
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    b.HasKey("PatientImmunizationRecordID");

                    b.HasIndex("PatientID")
                        .HasDatabaseName("FK_ImmunizationRecord_Patient");

                    b.ToTable("ImmunizationRecords");
                });

            modelBuilder.Entity("MultiFKRecExample.Models.Patient", b =>
                {
                    b.Property<int>("PatientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PatientID")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("PatientID");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("MultiFKRecExample.Models.ImmunizationRecord", b =>
                {
                    b.HasOne("MultiFKRecExample.Models.Patient", "PatientData")
                        .WithMany("Immunizations")
                        .HasForeignKey("PatientID")
                        .HasConstraintName("FK_ImmunizationRecord_Patient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatientData");
                });

            modelBuilder.Entity("MultiFKRecExample.Models.Patient", b =>
                {
                    b.Navigation("Immunizations");
                });
#pragma warning restore 612, 618
        }
    }
}
